-- Notes: API route DELETE /api/account uses auth.admin.deleteUser (service role).
-- Set SUPABASE_SERVICE_ROLE_KEY in .env.local (see repo .env.example) and in production env.
--
-- If deletion returns "Database error deleting user", run account-delete-fk-cascade.sql
-- in the SQL Editor (profiles / posts FKs to auth.users usually need ON DELETE CASCADE).
